### ISSUE TITLE
Dr连不上

### ISSUE THREAD

**Issue by xunan007** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#1]
![image](https://user-images.githubusercontent.com/19498847/53738385-0b92d980-3eca-11e9-9b99-af9cf00acb22.png)
请问下，最终这里 连不上是什么情况？

**Comment by xunan007** [comment]
自己已解决谢谢~

**Comment by shengqiangzhang** [comment]
这个提示一般是等几分钟就好了，还是不行的话可能是账号密码没输入对

**Comment by ileadall42** [comment]
@shengqiangzhang @stevennzhou 请问你是怎么解决的呢？如果我的线插入了lan口，重启路由器后192.168.1.1 就被拦截了，界面进不去，路由器也登不上去0 0

**Comment by shengqiangzhang** [comment]
@ileadall42 

极路由默认管理地址是192.168.1.199把，你刷完系统后地址才变192.168.1.1，路由器的lan插到电脑，这是对的，正常情况下能自动识别并分配给电脑ip，不行的话你手动设置下本机ip，192.168.1.x

**Comment by ileadall42** [comment]
@shengqiangzhang 我的路由器不是极路由，是个很老的领航者，刷openwrt 18.03 然后自己编译了一个drcom插件安装上去的，没有eth2 只有 0 和 1，wan一直提示Unknow error(USER_REQUEST) ，账号密码没有错..然后这个时候我把学校的那条线插到路由器之后，重启之后，192.168.1.1 就强制重定向到一个下载drcom客户端的页面了0 0 有空上qq 群通过以下0 0
