### ISSUE TITLE
手机连接断网

### ISSUE THREAD

**Issue by luketalk** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#11]
大佬 我按教程做了防检测 电脑连接一直不断线 手机连接后半小时左右就会断线

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786
