### ISSUE TITLE
极路由1s刷完后网速很慢

### ISSUE THREAD

**Issue by zetaflyer** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#12]
坐标广工大学城，用通过路由上网速度很慢，常常会网页都打不开。而不通过路由直接连接速度就飞快，不清楚哪里的问题....

**Comment by shengqiangzhang** [comment]
> 坐标广工大学城，用通过路由上网速度很慢，常常会网页都打不开。而不通过路由直接连接速度就飞快，不清楚哪里的问题....

是否开启了防检测，路由器是否老化？

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786
