### ISSUE TITLE
ua似乎会影响部分app

### ISSUE THREAD

**Issue by not-null-nil** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#13]
个人手机上（一加6t）bilibili加载不了视频
将教程给的ua换成微信内嵌浏览器的ua（从一加6t）获取
(Linux; Android 9; ONEPLUS A6010 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044705 Mobile Safari/537.36 MMWEBID/6994 MicroMessenger/7.0.4.1420(0x2700043C) Process/tools NetType/4G Language/en
后情况有所好转
由于个人比较菜，不能搞清楚是巧合还是有因果关系所以开了这个issue希望大佬可以看一下

**Comment by shengqiangzhang** [comment]
@MorosithIi 

Bilibili app设置中打开https播放选项

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786
