### ISSUE TITLE
安装时出现错误提示

### ISSUE THREAD

**Issue by SitandRelaxBen** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#15]
根据教程通过ssh安装现成插件时出现如下错误提示:
Unknown package 'gdut-drcom'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for gdut-drcom found, bu             t incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package gdut-drcom.

我也是准备在广工读书的（大学城校区），路由器是斐讯K2（PSG1218），固件版本是PandoraBox 19.01

**Comment by shengqiangzhang** [comment]
@SitandRelaxBn 

该项目发布的dr.com仅适用于openwrt系统，建议你备份下PandoraBox 固件，重刷入openwrt试试。

**Comment by SitandRelaxBen** [comment]
在OpenWRT下已经弄好了，谢谢xD
就等九月份开学后去实操了xD

**Comment by wb13143392629** [comment]
请问下大佬   install  privoxy提示不支持要怎么解决
