### ISSUE TITLE
k2p应用转发后http连接速度慢

### ISSUE THREAD

**Issue by CaffeineShawn** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#16]
朋友圈图片转菊花 b站走http仅有100+kb/s 是正常情况吗？

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786
