### ISSUE TITLE
手机上网慢

### ISSUE THREAD

**Issue by wb13143392629** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#17]
手机（iPhone6s）连wifi上网速度慢   微信收取信息  查看图片加载慢   电脑联网正常

**Comment by shengqiangzhang** [comment]
> 手机（iPhone6s）连wifi上网速度慢 微信收取信息 查看图片加载慢 电脑联网正常

没办法，修改http请求的ua会导致部分异常

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786
