### ISSUE TITLE
无法打开http://config.privoxy.org/edit-actions-list?f=0

### ISSUE THREAD

**Issue by nombre5** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#19]
使用 Privoxy 替换 UA。打开http://config.privoxy.org/edit-actions-list?f=0，如果打不开，请重启路由器多测试几遍。点击 Edit 按钮。

卡在这一步，多次往上查找重做，多次重启路由器但依然无法连接

**Comment by nombre5** [comment]
更换openwrt18061之后可以，可是重启后又不行

**Comment by shengqiangzhang** [comment]
> 更换openwrt18061之后可以，可是重启后又不行

清除浏览器记录，重启路由器等待连接上wifi后，再试试。如果不行，可能是前面步骤没设置对

**Comment by shengqiangzhang** [comment]
> 使用 Privoxy 替换 UA。打开[http://config.privoxy.org/edit-actions-list?f=0，如果打不开，请重启路由器多测试几遍。点击](http://config.privoxy.org/edit-actions-list?f=0%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%89%93%E4%B8%8D%E5%BC%80%EF%BC%8C%E8%AF%B7%E9%87%8D%E5%90%AF%E8%B7%AF%E7%94%B1%E5%99%A8%E5%A4%9A%E6%B5%8B%E8%AF%95%E5%87%A0%E9%81%8D%E3%80%82%E7%82%B9%E5%87%BB) Edit 按钮。
> 
> 卡在这一步，多次往上查找重做，多次重启路由器但依然无法连接

如果开了vpn，请务必关掉再访问
