### ISSUE TITLE
极路由1s刷完之后存在问题

### ISSUE THREAD

**Issue by V1CTORHS1N** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#2]
刷入openwrt固件并开启Dr.COM服务后网络速度很慢，而且手机接入无线网络后总会出现Wi-Fi挂起的问题，需要断线重连才能短暂的连接网络，求解。

**Comment by shengqiangzhang** [comment]
你刷的固件全名叫什么？

**Comment by shengqiangzhang** [comment]
> 刷入openwrt固件并开启Dr.COM服务后网络速度很慢，而且手机接入无线网络后总会出现Wi-Fi挂起的问题，需要断线重连才能短暂的连接网络，求解。

你刷的固件全名叫什么？固件确定刷对了吗？

**Comment by V1CTORHS1N** [comment]
固件为 openwrt-18.06.2-ramips-mt76x8-hc5661a-squashfs-sysupgrade.bin，是在你提供的链接中下载的。

**Comment by shengqiangzhang** [comment]
> 固件为 openwrt-18.06.2-ramips-mt76x8-hc5661a-squashfs-sysupgrade.bin，是在你提供的链接中下载的。

你是极路由1S（hc5661a）吧，如果是的话，应该就没刷错。至于你说网络卡，电脑端也卡么？还是只有手机端卡？
一般情况下，如果电脑也卡，那应该是本身网络的问题了。

WIFI经常挂起的问题我没遇见过，看看是不是信道的问题？

**Comment by V1CTORHS1N** [comment]
是的，路由器是极路由1S（hc5661a），电脑端和手机端都卡，用路由器拨号与用电脑直接拨号间网速的差距接近100%，有可能是固件配置的问题吗？

**Comment by shengqiangzhang** [comment]
> 是的，路由器是极路由1S（hc5661a），电脑端和手机端都卡，用路由器拨号与用电脑直接拨号间网速的差距接近100%，有可能是固件配置的问题吗？

你有多余的网线么？直接连接路由器和电脑，看看网络怎么样？一般来说这个固件没啥大问题的，可能是WIFI出现问题，你先用网线连电脑和路由器，看看不通过WIFI的网速是怎么样的？

还是用路由器拨号，只不过电脑直接连到路由器上网试试

**Comment by V1CTORHS1N** [comment]
不通过路由器连接校园网
![screenshot01](https://user-images.githubusercontent.com/48150320/53877792-132abd80-4045-11e9-9d6f-108a79dee15d.png)
使用网线通过路由器连接校园网
![screenshot02](https://user-images.githubusercontent.com/48150320/53877828-2ccc0500-4045-11e9-9daf-a3c199d459d4.png)
使用Wi-Fi连接校园网
![screenshot03](https://user-images.githubusercontent.com/48150320/53877921-74eb2780-4045-11e9-8b52-a65b9aab5340.png)

**Comment by shengqiangzhang** [comment]
> 不通过路由器连接校园网
> ![screenshot01](https://user-images.githubusercontent.com/48150320/53877792-132abd80-4045-11e9-9d6f-108a79dee15d.png)
> 使用网线通过路由器连接校园网
> ![screenshot02](https://user-images.githubusercontent.com/48150320/53877828-2ccc0500-4045-11e9-9daf-a3c199d459d4.png)
> 使用Wi-Fi连接校园网
> ![screenshot03](https://user-images.githubusercontent.com/48150320/53877921-74eb2780-4045-11e9-8b52-a65b9aab5340.png)

目前不能确定原因，你可以实时低版本的openwrt固件或者lede固件，试试效果，你这个问题第一次遇到，其实有时候可能是你的路由器用太久出现硬件问题。

欢迎你点击star和fork本项目哈，会持续更新，如果你解决了这个问题，也可以提醒我更新教程哈。

**Comment by V1CTORHS1N** [comment]
请问你能给我 /etc/config/wireless 的配置详情吗？

**Comment by shengqiangzhang** [comment]
> 请问你能给我 /etc/config/wireless 的配置详情吗？

基本不需要设置的，设置WIFI名称和密码就好了。网速问题你如果有其他路由器，可以重新刷一个试试，有可能是硬件问题的。并且，openwrt固件网速确实会比平常的时候慢一点，但是应该不会慢很多。你可以下载潘多拉固件，试试效果

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786

**Comment by V1CTORHS1N** [comment]
十分感谢你的努力和付出~
