### ISSUE TITLE
k2p专用文件drcom

### ISSUE THREAD

**Issue by CaffeineShawn** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#21]
start-stop-daemon: can't execute '/usr/bin/gdut-drcom': No such file or directory
tmp目录下出现drcom报错日志如上
然后路由器一分钟掉一次线 请问这个问题应该如何处理

**Comment by CaffeineShawn** [comment]
以上问题是在cc 1.7.2下出现的，尝试刷入k2p专用文件中的openwrt 18.06后有线无线均无法连接至路由器，只能在breed下连接。路由器是k2p银色b1

**Comment by shengqiangzhang** [comment]
> 以上问题是在cc 1.7.2下出现的，尝试刷入k2p专用文件中的openwrt 18.06后有线无线均无法连接至路由器，只能在breed下连接。路由器是k2p银色b1

你好，k2p我没有试过，如果有问题，建议你联系https://github.com/Xue-JW
看看他能不能帮到你。

还有，其他k2p的无线驱动是不开源的，所以就算成功刷了，也不能使用无线，建议你买个极路由1s一劳永逸吧。
