### ISSUE TITLE
WAN拨号存在问题

### ISSUE THREAD

**Issue by lizhh268** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#23]
我的是极路由1s，按照教程走了一遍。发现wan拨号有时成功（uptime,tx,rx都有数据）。但是没一分钟就断。而且拨号成功时也没有能连接上网络。还有个小疑问，就是复制mac地址到Drcom那里，需要把最后两位改吗（ 我改没改都试过了，都失败了）

**Comment by shengqiangzhang** [comment]
@Allon0 
1. 你是哪个学校
2. 请把network→interface页面截图发一下
3. 可以加群联系我

**Comment by lizhh268** [comment]
广工的呢。刚刚又试了下，发现这次拨号一直失败（半个钟了）。我之前成功是有多接了一条电脑到路由器上的时候。会不会是这个原因？
![Uploading 53.jpg…]()

**Comment by lizhh268** [comment]
![53](https://user-images.githubusercontent.com/58358869/69902197-863f4580-13c5-11ea-917b-265d09a28ea0.jpg)

**Comment by shengqiangzhang** [comment]
@Allon0 

目前可能是硬件问题，你到教程主页查看q群，群里面详细交流下。
