### ISSUE TITLE
【记录】小米路由器 4C 刷机过程

### ISSUE THREAD

**Issue by sikouhjw** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#27]
1. 按照《R4CM，说说我的小米路由器4C刷机过程：不用Linux也不用虚拟机……》[^1]获取 Breed；
2. 由于 OpenWrt 官网没有 4C 的 CPU 架构的固件，我找 1507488166（QQ 号）付费定制了一份 4C 的固件[^2]；
3. 按照 README[^3]去刷固件；
4. 由于固件内置了 Dr.com 插件及防检测插件（ttl，ipid，cookieflash，ua2f 最新版），无需再安装其它插件，只需配置信息即可；
5. 配置上网部分跟 README 几乎一致，只有『无线』部分略有差异，自行摸索即可，有一个下拉列表只选择 `LAN` 即可；
6. 重启后就可以正常上网了，如果出现直连网线有网、连 wifi 没网或连接不了的情况，尝试关机一段时间或者检查是否选择了 `LAN`。

[^1]: https://www.right.com.cn/FORUM/thread-4047571-1-1.html
[^2]: https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/8138729/Mi4C.zip
[^3]: https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#%E6%AD%A5%E9%AA%A4%E4%B8%89%E5%88%B7%E5%85%A5openwrt-%E7%B3%BB%E7%BB%9F%E5%9B%BA%E4%BB%B6

**Comment by shengqiangzhang** [comment]
@sikouhjw 感谢补充，该教程大体上是正确的，但是由于路由器版本众多，因此难免会有一些小错误。

openwrt官网是有4c的固件的，可能是由于教程提供的链接指向的是2018年的版本，经过检查，在20221版是有的，链接[https://archive.openwrt.org/releases/21.02.2/targets/ramips/mt76x8/openwrt-21.02.2-ramips-mt76x8-xiaomi_mi-router-4c-squashfs-sysupgrade.bin](https://archive.openwrt.org/releases/21.02.2/targets/ramips/mt76x8/openwrt-21.02.2-ramips-mt76x8-xiaomi_mi-router-4c-squashfs-sysupgrade.bin)

**Comment by jiqing112** [comment]
> 1. 按照《R4CM，说说我的小米路由器4C刷机过程：不用Linux也不用虚拟机……》[1](#user-content-fn-1-8b03f3a4c41e22c246b468d5fef3cd8e)获取 Breed；
> 2. 由于 OpenWrt 官网没有 4C 的 CPU 架构的固件，我找 1507488166（QQ 号）付费定制了一份 4C 的固件[2](#user-content-fn-2-8b03f3a4c41e22c246b468d5fef3cd8e)；
> 3. 按照 README[3](#user-content-fn-3-8b03f3a4c41e22c246b468d5fef3cd8e)去刷固件；
> 4. 由于固件内置了 Dr.com 插件及防检测插件（ttl，ipid，cookieflash，ua2f 最新版），无需再安装其它插件，只需配置信息即可；
> 5. 配置上网部分跟 README 几乎一致，只有『无线』部分略有差异，自行摸索即可，有一个下拉列表只选择 `LAN` 即可；
> 6. 重启后就可以正常上网了，如果出现直连网线有网、连 wifi 没网或连接不了的情况，尝试关机一段时间或者检查是否选择了 `LAN`。
> 
> ## Footnotes
> 1. https://www.right.com.cn/FORUM/thread-4047571-1-1.html [↩](#user-content-fnref-1-8b03f3a4c41e22c246b468d5fef3cd8e)
> 2. https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/8138729/Mi4C.zip [↩](#user-content-fnref-2-8b03f3a4c41e22c246b468d5fef3cd8e)
> 3. https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#%E6%AD%A5%E9%AA%A4%E4%B8%89%E5%88%B7%E5%85%A5openwrt-%E7%B3%BB%E7%BB%9F%E5%9B%BA%E4%BB%B6 [↩](#user-content-fnref-3-8b03f3a4c41e22c246b468d5fef3cd8e)

感谢楼主共享的附件。同小米4c ，第一次刷openwrt成功了。

听我说谢谢你，因为有你，温暖了四季。

**Comment by Eser-Tired** [comment]
感谢感谢，不用限制连接数了

**Comment by Ikaros-521** [comment]
> @sikouhjw 感谢补充，该教程大体上是正确的，但是由于路由器版本众多，因此难免会有一些小错误。
> 
> openwrt官网是有4c的固件的，可能是由于教程提供的链接指向的是2018年的版本，经过检查，在20221版是有的，链接https://archive.openwrt.org/releases/21.02.2/targets/ramips/mt76x8/openwrt-21.02.2-ramips-mt76x8-xiaomi_mi-router-4c-squashfs-sysupgrade.bin

刷的这个固件 一直重启。。。

**Comment by jiqing112** [comment]
> > @sikouhjw 感谢补充，该教程大体上是正确的，但是由于路由器版本众多，因此难免会有一些小错误。
> > openwrt官网是有4c的固件的，可能是由于教程提供的链接指向的是2018年的版本，经过检查，在20221版是有的，链接https://archive.openwrt.org/releases/21.02.2/targets/ramips/mt76x8/openwrt-21.02.2-ramips-mt76x8-xiaomi_mi-router-4c-squashfs-sysupgrade.bin
> 
> 刷的这个固件 一直重启。。。

我没有这个情况，你是不是哪一步做错了。刷不死了吗

**Comment by Ikaros-521** [comment]
> > > @sikouhjw 感谢补充，该教程大体上是正确的，但是由于路由器版本众多，因此难免会有一些小错误。
> > > openwrt官网是有4c的固件的，可能是由于教程提供的链接指向的是2018年的版本，经过检查，在20221版是有的，链接https://archive.openwrt.org/releases/21.02.2/targets/ramips/mt76x8/openwrt-21.02.2-ramips-mt76x8-xiaomi_mi-router-4c-squashfs-sysupgrade.bin
> > 
> > 
> > 刷的这个固件 一直重启。。。
> 
> 我没有这个情况，你是不是哪一步做错了。刷不死了吗

就是刷完Breed后，在里面加载的这个21.02.2的固件 更新上去的，然后更新完后，就一直在重启

**Comment by jiqing112** [comment]
> > > > @sikouhjw 感谢补充，该教程大体上是正确的，但是由于路由器版本众多，因此难免会有一些小错误。
> > > > openwrt官网是有4c的固件的，可能是由于教程提供的链接指向的是2018年的版本，经过检查，在20221版是有的，链接https://archive.openwrt.org/releases/21.02.2/targets/ramips/mt76x8/openwrt-21.02.2-ramips-mt76x8-xiaomi_mi-router-4c-squashfs-sysupgrade.bin
> > > 
> > > 
> > > 刷的这个固件 一直重启。。。
> > 
> > 
> > 我没有这个情况，你是不是哪一步做错了。刷不死了吗
> 
> 就是刷完Breed后，在里面加载的这个21.02.2的固件 更新上去的，然后更新完后，就一直在重启

eeprom.bin刷了吗？
https://www.jianshu.com/p/20c83426cd9e

**Comment by Ikaros-521** [comment]
> bin

这个倒没有 哦吼！！！

**Comment by jiqing112** [comment]
蓝奏(带个eeprom备份)： https://wwn.lanzouy.com/iyhwZ05hohhg

**Comment by jiqing112** [comment]
> > bin
> 
> 这个倒没有 哦吼！！！

蓝奏(带个eeprom备份)： https://wwn.lanzouy.com/iyhwZ05hohhg

**Comment by Ikaros-521** [comment]
> > > bin
> > 
> > 
> > 这个倒没有 哦吼！！！
> 
> 蓝奏(带个eeprom备份)： https://wwn.lanzouy.com/iyhwZ05hohhg

eeprom 前面我备份的那个可以吗

**Comment by jiqing112** [comment]
> > > > bin
> > > 
> > > 
> > > 这个倒没有 哦吼！！！
> > 
> > 
> > 蓝奏(带个eeprom备份)： https://wwn.lanzouy.com/iyhwZ05hohhg
> 
> eeprom 前面我备份的那个可以吗

你看着来吧，都试试，正常了就行。

**Comment by Ikaros-521** [comment]
> > > > > bin
> > > > 
> > > > 
> > > > 这个倒没有 哦吼！！！
> > > 
> > > 
> > > 蓝奏(带个eeprom备份)： https://wwn.lanzouy.com/iyhwZ05hohhg
> > 
> > 
> > eeprom 前面我备份的那个可以吗
> 
> 你看着来吧，都试试，正常了就行。

行 感谢大佬，等会试试看

**Comment by Ikaros-521** [comment]
> > > > > bin
> > > > 
> > > > 
> > > > 这个倒没有 哦吼！！！
> > > 
> > > 
> > > 蓝奏(带个eeprom备份)： https://wwn.lanzouy.com/iyhwZ05hohhg
> > 
> > 
> > eeprom 前面我备份的那个可以吗
> 
> 你看着来吧，都试试，正常了就行。

还是不行 一样会重启 头疼

**Comment by Ikaros-521** [comment]
> > > > > bin
> > > > 
> > > > 
> > > > 这个倒没有 哦吼！！！
> > > 
> > > 
> > > 蓝奏(带个eeprom备份)： https://wwn.lanzouy.com/iyhwZ05hohhg
> > 
> > 
> > eeprom 前面我备份的那个可以吗
> 
> 你看着来吧，都试试，正常了就行。

还是不行 一样会重启 头疼

**Comment by kaiser20106** [comment]
我是wan直接DHCP上网，不用DrCom，有没有哪个软件包是可以卸载的？内存已经占用了95%了

**Comment by sikouhjw** [comment]
> 我是wan直接DHCP上网，不用DrCom，有没有哪个软件包是可以卸载的？内存已经占用了95%了

不清楚……因为固件是别人做的，我不懂里面的东西。我使用时内存还有挺多的……
![图片](https://user-images.githubusercontent.com/49770925/223702830-321887ad-bd35-4067-ac00-278139ca4cf1.png)

**Comment by kaiser20106** [comment]
是这个页面
![image](https://user-images.githubusercontent.com/75980075/223723450-bea1fd00-fcdb-4d26-9ba1-ad1c4cf59619.png)

**Comment by FrzMtrsprt** [comment]
如果以后有人刷4C无限重启看到这个issue，可能是因为你用breed刷入了官方固件，需要修改breed的固件刷入地址和启动地址，详见[教程](https://cloudflare.luhawxem.com/2021/05/19/Mi-Router-4C-flash-openwrt/)。

**Comment by hamedalwseli** [comment]
what is the password for login ?

**Comment by jiqing112** [comment]
> what is the password for login ?

“password”

**Comment by hamedalwseli** [comment]
Hello, Professor. Thank you for your reply. I wanted to ask you about the
TP-Link WR842N v7 or v4.x device. Do you have any experience with how to
flash OpenWRT or any other system that supports VLANs onto it? I have
several of these devices and I want to flash the system onto them. If you
could help me with this, I would be very grateful.
