### ISSUE TITLE
隔一分钟重连一次

### ISSUE THREAD

**Issue by Xue-JW** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#3]
完全按照教程走了一遍，但是拨号不稳定，几乎每分钟断一次，是心跳包不对更新了？
和教程不同的是我不是eth0.2而是eth0.1，是因为这个吗？
目前是否还需要使用Privoxy避免检测？这个方法会影响很多软件上网

**Comment by Xue-JW** [comment]
斐讯k2p，重新刷了潘多拉，试着自己编译了一个drcom，和教程一样是eth0.2了，但是还是每分钟重连

**Comment by Xue-JW** [comment]
看到tmp文件夹里有如下错误日志，不知道是不是正常：start-stop-daemon: can't execute '/usr/bin/gdut-drcom': No such file or directory

**Comment by shengqiangzhang** [comment]
> 看到tmp文件夹里有如下错误日志，不知道是不是正常：start-stop-daemon: can't execute '/usr/bin/gdut-drcom': No such file or directory

我帮你找一下看看是否有现成固件，请问你是哪个学校，顺便提供下你的邮箱

**Comment by Xue-JW** [comment]
我是广工的，a9154@vip.qq.com,不完美的解决了，下openwrt的官方版，可以稳定拨号，但是因为k2p的驱动闭源所以在openwrt无法使用wifi，只能另外再加一个路由器开wifi，我试过很多其他固件都不行，装了插件但是拨号会断，潘多拉有wifi，但是安装不正常，似乎要下载一个几百兆的sdk编译安装包。

**Comment by shengqiangzhang** [comment]
确实是，openwrt
k2p无wifi，潘多拉drcom插件过阵子闲下来我编译一个正常的。用两个路由器记得使用交换机模式，关闭dhcp，否则可能也会掉线。

Gavin <notifications@github.com>于2019年3月16日 周六下午11:57写道：

**Comment by Xue-JW** [comment]
好的，感谢！目前我是拨号路由器的lan口接在放wifi路由器的wan口用dhcp，并且没隐藏user-agent，也挺稳定的，看来有可能不同区域管理严格程度不一样，我找的的sdk地址：https://www.zhihu.com/question/39103161

**Comment by Xue-JW** [comment]
[k2p校园网可用.zip](https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/2974860/k2p.zip)
把我使用的东西发上来也许有人需要

**Comment by shengqiangzhang** [comment]
> [k2p校园网可用.zip](https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/2974860/k2p.zip)
> 把我使用的东西发上来也许有人需要

这个是打包的完整固件么？包括drom和privoxy？

**Comment by shengqiangzhang** [comment]
> [k2p校园网可用.zip](https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/2974860/k2p.zip)
> 把我使用的东西发上来也许有人需要

好的

**Comment by shengqiangzhang** [comment]
> [k2p校园网可用.zip](https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/2974860/k2p.zip)
> 把我使用的东西发上来也许有人需要

好的，你的drcom插件是自己编译的还是用我发布的？

**Comment by Xue-JW** [comment]
> > [k2p校园网可用.zip](https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/2974860/k2p.zip)
> > 把我使用的东西发上来也许有人需要
> 
> 好的，你的drcom插件是自己编译的还是用我发布的？

这份是你发布的，我自己编译的感觉效果一样

**Comment by xima6371** [comment]
> > > [k2p校园网可用.zip](https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/2974860/k2p.zip)
> > > 把我使用的东西发上来也许有人需要
> > 
> > 
> > 好的，你的drcom插件是自己编译的还是用我发布的？
> 
> 这份是你发布的，我自己编译的感觉效果一样

固件：pandorabox
路由：k2p
你好，我也遇到同样的问题，用这个zip的文件仍然一分钟断一次(eth0.2)，而且还会出现无线未开启或未关联的情况，就连不上wifi。

在open [[[cc(1.7到1.72)固件下，保存并应用privoxy会出现[图](http://ww1.sinaimg.cn/large/006S5wgFly1g1qnp00onej30w0054aag.jpg)。。异常蛋疼。。兄弟你的k2p搞定了吗

**Comment by Xue-JW** [comment]
> > > > [k2p校园网可用.zip](https://github.com/shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt/files/2974860/k2p.zip)
> > > > 把我使用的东西发上来也许有人需要
> > > 
> > > 
> > > 好的，你的drcom插件是自己编译的还是用我发布的？
> > 
> > 
> > 这份是你发布的，我自己编译的感觉效果一样
> 
> 固件：pandorabox
> 路由：k2p
> 你好，我也遇到同样的问题，用这个zip的文件仍然一分钟断一次(eth0.2)，而且还会出现无线未开启或未关联的情况，就连不上wifi。
> 
> 在open [[[cc(1.7到1.72)固件下，保存并应用privoxy会出现[图](http://ww1.sinaimg.cn/large/006S5wgFly1g1qnp00onej30w0054aag.jpg)。。异常蛋疼。。兄弟你的k2p搞定了吗

国内任何第三方的基本都不行，不能正常安装使用，只能使用官网版本openwrt，(下载地址压缩包好像有),但没有添加闭源的wifi驱动，所以没wifi,除非自己编译添加
