### ISSUE TITLE
您好，我现在是自己编译固件，想直接把您的dr.com代码

### ISSUE THREAD

**Issue by liqine** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#4]
您好，我用您的方法可以生成ipk。我现在想完全自己编译固件，想直接把您的dr.com代码直接编译进固件里面去，应该怎么操作呢，，刚开始接触openwrt，希望大佬指点下，感谢

**Comment by shengqiangzhang** [comment]
> 您好，我用您的方法可以生成ipk。我现在想完全自己编译固件，想直接把您的dr.com代码直接编译进固件里面去，应该怎么操作呢，，刚开始接触openwrt，希望大佬指点下，感谢

你好，这个三言两语说不完，简单来说就是固件的解包、打包过程，需要使用一些工具进行解包再打包。可以直接把ipk打包到现有的固件中，生成新的固件。我发几个地址给你，你有时间的话研究下。
https://www.right.com.cn/forum/thread-265211-1-1.html
https://www.right.com.cn/FORUM/forum.php?mod=viewthread&tid=353543
https://blog.csdn.net/u014795817/article/details/74505666?utm_source=blogxgwz0
https://www.v2ex.com/t/156607

**Comment by shengqiangzhang** [comment]
> 您好，我用您的方法可以生成ipk。我现在想完全自己编译固件，想直接把您的dr.com代码直接编译进固件里面去，应该怎么操作呢，，刚开始接触openwrt，希望大佬指点下，感谢

你好，这个三言两语说不完，简单来说就是固件的解包、打包过程，需要使用一些工具进行解包再打包。可以直接把ipk打包到现有的固件中，生成新的固件。我发几个地址给你，你有时间的话研究下。
https://www.right.com.cn/forum/thread-265211-1-1.html
https://www.right.com.cn/FORUM/forum.php?mod=viewthread&tid=353543
https://blog.csdn.net/u014795817/article/details/74505666?utm_source=blogxgwz0
https://www.v2ex.com/t/156607

**Comment by shengqiangzhang** [comment]
如果我的方法解决了你的问题或者你已自行解决此问题，请自行关闭该issue

**Comment by liqine** [comment]
感谢
