### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by haoxianhe** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#5]
我发现了一些问题，开启防封检测以后，手机的哔哩哔哩app无法打开视频！

**Comment by shengqiangzhang** [comment]
> 我发现了一些问题，开启防封检测以后，手机的哔哩哔哩app无法打开视频！

你好，使用防代理检测后，会对http流量进行修改user-agent标志，导致部分app工作出现一点问题。你可以把bilibili的app设置开启https播放就好了。
教程
https://jingyan.baidu.com/article/f79b7cb3d511f89144023e2b.html
http://www.9ht.com/v/437.html

**Comment by shengqiangzhang** [comment]
如果我的方法解决了你的问题或者你已自行解决此问题，请自行关闭该issue

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786

**Comment by haoxianhe** [comment]
可惜，我已经毕业了！！！发自我的华为手机-------- 原始邮件 --------发件人： sqzhang <notifications@github.com>日期： 2019年9月24日周二 凌晨3:32收件人： shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt <Drcom-GDUT-HC5661A-OpenWrt@noreply.github.com>抄送： haoxianhe <hhx869017703@gmail.com>, Author <author@noreply.github.com>主    题： Re: [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt] 你好！ (#5)已解决，将UA修改为Privoxy 3.0.26

然后点submit，然后重启路由器即可。

欢迎加入广工Openwrt交流群，群聊号码：748317786
