### ISSUE TITLE
NTP服务器问题

### ISSUE THREAD

**Issue by zhuzai123** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#6]
大佬，我想问问强制与路由器同步ntp有何目的呢，还有你iptables规则上面对ntp强制目标地址转换那一行好像是要加上-p udp标明协议材能正常转换的⑧  :)

**Comment by shengqiangzhang** [comment]
这一步其实不是必须的，大部分学校不会检测。-p udp我忘记加了，可能是本身没影响，所以没发现，谢谢提醒哦。

**Comment by shengqiangzhang** [comment]
> 大佬，我想问问强制与路由器同步ntp有何目的呢，还有你iptables规则上面对ntp强制目标地址转换那一行好像是要加上-p udp标明协议材能正常转换的⑧ :)

这一步其实不是必须的，大部分学校不会检测。-p udp我忘记加了，可能是本身没影响，所以没发现，谢谢提醒哦。
