### ISSUE TITLE
网页编辑器问题

### ISSUE THREAD

**Issue by Subdue0** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#7]
大佬，为什么，网页编辑器http://config.privoxy.org/edit-actions-list?f=0有时为什么会打不开呢？Enable action file editor我已经勾选了的，配置的界面我是可以打开，而且可以查看配置就是编辑不了，我第一次配置使用privoxy的时候是可以使用网页编辑器的，后面重新配置之后就一直使用不了，虽然可以通过直接编辑配置文件修改配置，但我想知道为什么网页编辑器无法使用，重启多次依然没办法用，这种问题是怎么造成的？

**Comment by shengqiangzhang** [comment]
关闭ss等代理软件，然后重启路由器一般就可以了。

**Comment by shengqiangzhang** [comment]
> 大佬，为什么，网页编辑器[http://config.privoxy.org/edit-actions-list?f=0有时为什么会打不开呢？Enable](http://config.privoxy.org/edit-actions-list?f=0%E6%9C%89%E6%97%B6%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E6%89%93%E4%B8%8D%E5%BC%80%E5%91%A2%EF%BC%9FEnable) action file editor我已经勾选了的，配置的界面我是可以打开，而且可以查看配置就是编辑不了，我第一次配置使用privoxy的时候是可以使用网页编辑器的，后面重新配置之后就一直使用不了，虽然可以通过直接编辑配置文件修改配置，但我想知道为什么网页编辑器无法使用，重启多次依然没办法用，这种问题是怎么造成的？

关闭ss等代理软件，然后重启路由器一般就可以了。
