### ISSUE TITLE
部分app无法使用

### ISSUE THREAD

**Issue by kingfish12** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#8]
安卓端b站勾选启用https播放无法看番剧，可以看个人上传的视频
苹果端任何视频都无法看

**Comment by shengqiangzhang** [comment]
> 安卓端b站勾选启用https播放无法看番剧，可以看个人上传的视频
> 苹果端任何视频都无法看

勾选https后是可以看的，你可以重启下路由器。

其他情况的话，只能每天重启路由器的次数多一点，因为防代理检测就是把http的数据给混淆了，导致部分app播放异常。但是只要是走https的，就没有任何影响，走http如果不修改的话，就会掉线。

**Comment by shengqiangzhang** [comment]
已解决，将UA修改为Privoxy 3.0.26
然后点submit，然后重启路由器即可。


欢迎加入广工Openwrt交流群，群聊号码：748317786
