### ISSUE TITLE
你好 我们学校是5.2.1 D版的 应该怎么编译

### ISSUE THREAD

**Issue by luketalk** [shengqiangzhang/Drcom-GDUT-HC5661A-OpenWrt#9]
https://github.com/drcoms/drcom-generic/blob/master/custom/%E9%95%BF%E6%B2%99%E8%81%94%E9%80%9A.py
 用的这个py  麻烦大佬指点一下

**Comment by shengqiangzhang** [comment]
> https://github.com/drcoms/drcom-generic/blob/master/custom/%E9%95%BF%E6%B2%99%E8%81%94%E9%80%9A.py
> 用的这个py 麻烦大佬指点一下

教程中的这个步骤：
#然后再进入package文件夹，并下载drcom ODP文件夹
cd package && git clone https://github.com/GJXS1980/ODP.git

其中，打开https://github.com/GJXS1980/ODP.git就是根据https://github.com/drcoms/drcom-generic/编译而来的，至于怎么编译，这个网站已经有说明了。

**Comment by luketalk** [comment]
能麻烦详细说一下吗 没有找到
